get "/", forward: "/index.groovy"
get "/upload", forward: "/upload.groovy"
get "/api/startingSet", forward: "/api.groovy"
get "/api/complete", forward: "/apiFull.groovy"
get "/api/getTime", forward: "/timeApi.groovy"